version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3308 -- npm start'
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3308:3308
    environment:
      MYSQL_DATABASE: db_proposta
      MYSQL_USER: proposta
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234