
version: '3'
services:
  mysql_db:
    image: mysql:8.0
    restart: always
    environment: 
      - MYSQL_USER=proposta
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_proposta
      - MYSQL_PASSWORD=12345
    ports: 
      - "3306:3306"
    networks: 
      - proposta-network

  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    depends_on: 
      - "mysql_db"
    ports: 
    - "8080:8080"
    environment: 
      - DATABASE_HOST=mysql_db
      - DATABASE_USER=proposta  
      - DATABASE_PASSWORD=12345  
      - DATABASE_NAME=db_proposta  
      - DATABASE_PORT=336
    networks: 
      - proposta-network

networks: 
    proposta-network:
        driver: bridge